tls:
  certificates:
    - certFile: /etc/certs/mphome.crt
      keyFile: /etc/certs/mphome.key
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"

http:
  routers:
    dashboard:
      entryPoints:
        - "websecure"
        - "web"
      rule: "Host(`traefik.mphome.com`) || Host(`rhel9.mphome.com`)"
      service: "api@internal"
      tls: true
    whoami:
      entryPoints:
        - "websecure"
      rule: "Host(`whoami.mphome.com`)"
      tls: true
      service: "whoami-my-traefik@docker"

